name: 'Check'
on:
  pull_request:
  workflow_dispatch:
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  integration-tests:
    name: 'Tests'
    runs-on: [self-hosted, linux, normal]
    steps:
      - name: 'Check out code'
        uses: actions/checkout@v3
        with:
            submodules: recursive
      - name: 'Build Docker image'
        run: |
          COMMIT=$(git rev-parse --short=7 HEAD)
          K_VERSION=$(cat deps/k_release)

          docker build .                        \
            --file .github/workflows/Dockerfile \
            --build-arg K_VERSION=${K_VERSION}  \
            --tag runtimeverificationinc/proof-checker-ci:${COMMIT}

          docker run                   \
            --name proof-checker-ci \
            --rm                       \
            --interactive              \
            --tty                      \
            --detach                   \
            --workdir /home/user       \
            runtimeverificationinc/proof-checker-ci:${COMMIT}

          docker cp . proof-checker-ci:/home/user
          docker exec proof-checker-ci chown -R user:user /home/user
      - name: 'Set Python version'
        run: docker exec --user user proof-checker-ci poetry env use 3.10
      - name: 'Run code quality checks'
        run: make -C generation check
      - name: 'Run pyupgrade'
        run: make -C generation pyupgrade
      - name: 'Run unit tests'
        run: make -C 'generation' cov-unit
      - name: 'Run rust tests'
        run: cargo test
      - name: 'Run integration tests'
        run: docker exec --user user proof-checker-ci make -C generation cov-integration COV_ARGS=-n8
      - name: 'Tear down Docker container'
        if: always()
        run: |
          docker stop --time=0 proof-checker-ci
